name: Deploy to Render

on:
  push:
    branches:
      - main  # 或者其他你想监听的分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Output environment variables (for debugging purposes)
      run: |
        echo "ACCOUNT: ${{ secrets.ACCOUNT }}"
        echo "PASSWORD: ${{ secrets.PASSWORD }}"

    - name: Notify Render
      run: |
        curl -X POST "https://api.render.com/deploy/srv-xxxxxx" \
        -H 'Accept: application/json' \
        -H 'Authorization: Bearer ${{ secrets.RENDER_API_KEY }}' \
        -d '{"account": "${{ secrets.ACCOUNT }}", "password": "${{ secrets.PASSWORD }}"}'
      env:
        ACCOUNT: ${{ secrets.ACCOUNT }}
        PASSWORD: ${{ secrets.PASSWORD }}
